### ISSUE TITLE
demo.py deletes itself

### ISSUE THREAD

**Issue by Ianmcmill** [MotorCityCobra/face_ripper_9000#5]
Windows 10
All deps working

When issuing
`python demo.py -i D:\fakes\data\target.jpg -v D:\fakes\data\mp4dir\`

I get this:

```
Target filename: D:\fakes\data\target.jpg.
Video input directory: D:\fakes\data\mp4dir.
Tolerance: 0.6.
Number of confirmed faces saved from each video: 1000.                          
Using OpenCL: True.
Output directory: D:\fakes\data\mp4dir_output.                                
Scanned videos will be moved to: D:\fakes\data\mp4dir_scanned_vids.
Moving demo.py to the too small folder
Moving LICENSE to the too small folder                                          
Moving README.md to the too small folder
Now double checking there is only one face in each photo
```

And all files are moved to the too small folder and renamed into jpgs and nothing else is extracted.
too small-0cIqXbWehwKRcTtt.jpg

EDIT
on the second try with the exact same command (after I unpcked the py again) everything worked. Seems still like a logic mistake.

**Comment by Ianmcmill** [comment]
I guess this just comes from my own mistake. Can be closed

**Comment by MotorCityCobra** [comment]
Glad you sorted it out.  
It has to change the working directory at one point.  

I've had this happen to me too. Vaguely remember what fixed it.

**Comment by deepshakes** [comment]
Same thing happened to me, but for anyone facing the same problem, I had to delete `pic_output`, `pic_scanned_vids` and `pic_too_small` on top of recreating demo.py to get it running
